- title: A Case for In-Memory Random Scatter-Gather for Fast Graph Processing
  authors:
    - Changmin Shin<sup>1</sup>
    - Taehee Kwon<sup>1</sup>
    - Jaeyong Song
    - Jae Hyung Ju
    - Frank Liu
    - Jinho Lee
  date: '2024-03-10'
  publisher: IEEE Computer Architecture Letters (CAL)
  tags:
    - SCI
    - Arch.

- title: "PeerAiD: Improving Adversarial Distillation from a Specialized Peer Tutor"
  authors:
    - Jaewon Jung
    - Hongsun Jang
    - Jaeyong Song
    - Jinho Lee
  date: '2024-03-09'
  publisher: Computer Vision and Pattern Recognition Conference (CVPR)
  tags:
    - Top Conf.
    - AI/ML

- id: https://doi.org/10.1145/3627535.3638474
  publisher: ACM Annual Symposium on Principles and Practice of Parallel Programming (PPoPP)
  buttons:
  - type: paper
    link: https://dl.acm.org/doi/10.1145/3627535.3638474
  - type: artifact
    link: https://zenodo.org/records/10462237
  tags:
    - Top Conf.
    - Bioinfo.
    - Syst. SW

- title: "Pipette: Automatic Fine-Grained Large Language Model Training Configurator for Real-World Clusters"
  authors:
    - Jinkyu Yim<sup>1</sup>
    - Jaeyong Song<sup>1</sup>
    - Yerim Choi
    - Jaebeen Lee
    - Hongsun Jang
    - Jinho Lee
  date: '2024-03-27'
  publisher: Design, Automation and Test in Europe Conference (DATE)
  tags:
    - Top Conf.
    - AI/ML
    - Syst. SW

- title: "Smart-Infinity: Fast Large Language Model Training using Near-Storage Processing on a Real System"
  authors:
    - Hongsun Jang
    - Jaeyong Song
    - Jaewon Jung
    - Jaeyoung Park
    - Youngsok Kim
    - Jinho Lee
  date: '2024-03-02'
  publisher: Best Paper Award-Honorable Mention, International Symposium on High-Performance Computer Architecture (HPCA)
  buttons:
    - type: arxiv
      link: http://arxiv.org/abs/2403.06664
    - type: github
      link: https://github.com/AIS-SNU/smart-infinity
    - type: video
      link: https://www.youtube.com/watch?v=o1O3-mQCSv4&feature=youtu.be
    - type: poster
      link: https://github.com/AIS-SNU/smart-infinity/blob/main/assets/smart-infinity_poster_hpca24.pdf
  tags:
    - Top Conf.
    - Syst. SW
    - Arch. 
    - AI/ML


- id: doi:10.1109/DAC18074.2021.9586121
  type: paper
  image: images_paper/dance.png
  authors:
    - Kanghyun Choi<sup>1</sup>
    - Deokki Hong<sup>1</sup>
    - Hojae Yoon<sup>1</sup>
    - Joonsang Yu 
    - Youngsok Kim
    - Jinho Lee
  buttons:
    - type: arxiv
      link: https://arxiv.org/abs/2009.06237
    - type: slide
      link: resources_paper/dance_slides.pdf
  publisher: Design Automation Conference (DAC)
  tags:
    - Top Conf. 
    - AI/ML 
    - Arch.

- id: arxiv:2111.02625
  type: paper
  image: images_paper/qimera.png
  publisher: Neural Information Processing Systems (NeurIPS)
  buttons:
    - type: arxiv
      link: https://arxiv.org/abs/2111.02625
    - type: slide
      link: resources_paper/qimera_slides.pdf
    - type: github
      link: https://github.com/iamkanghyunchoi/qimera
  tags:
    - Top Conf. 
    - AI/ML 

- id: arxiv:2301.09312
  type: paper
  image: images_paper/hdx.png
  publisher: Design Automation Conference (DAC)
  buttons:
    - type: arxiv
      link: https://arxiv.org/abs/2301.09312
  tags:
    - Top Conf. 
    - AI/ML 
    - Arch.

- id: arxiv:2203.17008
  type: paper
  image: images_paper/ait.png
  publisher: Neural Information Processing Systems (NeurIPS)
  buttons:
    - type: arxiv
      link: https://arxiv.org/abs/2203.17008
    - type: slide
      link: resources_paper/cvpr_ait.pdf
    - type: github
      link: https://github.com/iamkanghyunchoi/ait
  tags:
    - Top Conf. 
    - AI/ML 

- id: doi:10.1109/DAC56929.2023.10247930
  type: paper
  image: images_paper/dbac.png
  publisher: Design Automation Conference (DAC)
  tags:
    - Top Conf. 
    - AI/ML 