- title: "DANCE++: Differentiable Accelerator/Network Co-Exploration with Hard Constraints and Data-Free Training for Real-World Scenarios"
  authors:
    - Kanghyun Choi
    - Deokki Hong
    - Hyeyoon Lee
    - Joonsang Yu
    - Noseong Park
    - Youngsok Kim
    - Jinho Lee
  date: '2025-06-13'
  publisher: IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems (TCAD)
  tags:
    - SCI
    - AI/ML 
    - Arch.
  image: images_paper/dance++_overview.png
  id: ""


- title: "PathWeaver: A High-Throughput Multi-GPU System for Graph-Based Approximate Nearest Neighbor Search"
  authors:
    - Sukjin Kim
    - Seongyeon Park
    - Junguk Hong
    - Hunseong Lim
    - Si Ung Noh
    - Taehee Kwon
    - Jinho Lee
  date: '2025-07-07'
  publisher: USENIX Annual Technical Conference (USENIX ATC)
  tags:
    - Top Conf.
    - Syst. SW
  image: images_paper/pathweaver.png
  id: ""

- title: "G³SA: A GPU-Accelerated Gold Standard Genomics Library for End-to-End Sequence Alignment"
  authors:
    - Yeejoo Han
    - Sunwoo Kim
    - Seongyeon Park
    - Jinho Lee
  date: '2025-06-08'
  publisher: International Conference on Supercomputing (ICS)
  tags:
    - Top Conf.
    - AI/ML
  image: images_paper/g3sa.jpg
  id: ""

- title: "MimiQ: Low-Bit Data-Free Quantization of Vision Transformers with Encouraging Inter-Head Attention Similarity"
  authors:
    - Kanghyun Choi
    - Hyeyoon Lee
    - Dain Kwon
    - SunJong Park
    - Kyuyeun Kim
    - Noseong Park
    - Jonghyun Choi
    - Jinho Lee
  date: '2025-02-25'
  publisher: AAAI Conference on Artificial Intelligence (AAAI)
  tags:
    - Top Conf.
    - AI/ML
  image: images_paper/mimiq.png
  id: "10.1609/aaai.v39i15.33761"

- title: "Piccolo: Large-Scale Graph Processing with Fine-Grained In-Memory Scatter-Gather"
  authors:
    - Changmin Shin
    - Jaeyong Song
    - Hongsun Jang
    - Dogeun Kim
    - Jun Sung
    - Taehee Kwon
    - Jae Hyung Ju
    - Frank Liu
    - Yeonkyu Choi
    - Jinho Lee
  date: '2025-03-01'
  publisher: International Symposium on High-Performance Computer Architecture (HPCA)
  tags:
    - Top Conf.
    - Arch.
  image: images_paper/piccolo_hpca.png
  id: "10.1109/HPCA61900.2025.00055"


- title: "GraNNDis: Fast Distributed Graph Neural Network Training Framework for Multi-Server Clusters"
  authors:
    - Jaeyong Song
    - Hongsun Jang
    - Hunseong Lim
    - Jaewon Jung
    - Youngsok Kim
    - Jinho Lee
  date: '2024-10-13'
  publisher: The International Conference on Parallel Architectures and Compilation Techniques (PACT)
  buttons:
    - type: arxiv
      link: https://arxiv.org/abs/2311.06837
  tags:
    - Top Conf.
    - AI/ML
    - Syst. SW
  image: images_paper/granndis.png
  id: "10.1145/3656019.3676892"

- title: "DataFreeShield: Defending Adversarial Attacks without Training Data"
  authors:
    - Hyeyoon Lee
    - Kanghyun Choi
    - Dain Kwon
    - SunJong Park
    - Mayoore Selvarasa Jaiswal
    - Noseong Park
    - Jonghyun Choi
    - Jinho Lee
  date: '2024-05-02'
  publisher: International Conference on Machine Learning (ICML)
  tags:
    - Top Conf.
    - AI/ML
  image: images_paper/dfshield.png
  id: 10.48550/arXiv.2406.15635

- title: "PID-Comm: A Fast and Flexible Collective Communication Framework for Commodity Processing-in-DIMMs"
  authors:
    - Si Ung Noh<sup>1</sup>
    - Junguk Hong<sup>1</sup>
    - Chaemin Lim
    - Seongyeon Park
    - Jeehyun Kim
    - Hanjun Kim
    - Youngsok Kim
    - Jinho Lee
  date: '2024-07-01'
  publisher: International Symposium on Computer Architecture (ISCA)
  tags:
    - Top Conf.
    - Arch.
    - Syst. SW
  image: images_paper/PIDComm.png
  id: 10.1109/ISCA59077.2024.00027

- title: A Case for In-Memory Random Scatter-Gather for Fast Graph Processing
  authors:
    - Changmin Shin<sup>1</sup>
    - Taehee Kwon<sup>1</sup>
    - Jaeyong Song
    - Jae Hyung Ju
    - Frank Liu
    - Jinho Lee
  date: '2024-03-10'
  publisher: IEEE Computer Architecture Letters (CAL)
  tags:
    - SCI
    - Arch.
  image: images_paper/piccolo_cal.png
  id: 10.1109/LCA.2024.3376680

- title: "PeerAiD: Improving Adversarial Distillation from a Specialized Peer Tutor"
  authors:
    - Jaewon Jung
    - Hongsun Jang
    - Jaeyong Song
    - Jinho Lee
  date: '2024-03-09'
  publisher: Computer Vision and Pattern Recognition Conference (CVPR)
  buttons:
  - type: arxiv
    link: https://arxiv.org/abs/2403.06668
  - type: github
    link: jaewonalive/PeerAiD
  - type: video
    link: https://youtu.be/qxQiHhbQ8kU?si=ecHV3H1AAbWHDSVx
  - type: poster
    link: https://github.com/jaewonalive/PeerAiD/blob/main/assets/PeerAiD_poster_cvpr24.pdf
  - type: slide
    link: https://docs.google.com/presentation/d/1nY40LIQVsDLaIvnlu-DSANVl_NzTcsR3/edit?usp=drive_link

  tags:
    - Top Conf.
    - AI/ML
  image: images_paper/PeerAiD_poster_cvpr24.png
  id: 10.48550/arXiv.2403.06668

- id: 10.1145/3627535.3638474
  publisher: ACM Annual Symposium on Principles and Practice of Parallel Programming (PPoPP)
  image: images_paper/agatha.png
  buttons:
  - type: paper
    link: https://dl.acm.org/doi/10.1145/3627535.3638474
  - type: artifact
    link: https://zenodo.org/records/10462237
  tags:
    - Top Conf.
    - Bioinfo.
    - Syst. SW

- title: "Pipette: Automatic Fine-Grained Large Language Model Training Configurator for Real-World Clusters"
  authors:
    - Jinkyu Yim<sup>1</sup>
    - Jaeyong Song<sup>1</sup>
    - Yerim Choi
    - Jaebeen Lee
    - Jaewon Jung
    - Hongsun Jang
    - Jinho Lee
  date: '2024-03-27'
  publisher: Design, Automation and Test in Europe Conference (DATE)
  tags:
    - Top Conf.
    - AI/ML
    - Syst. SW
  image: images_paper/pipette_overall.png
  id: 10.23919/DATE58400.2024.10546826

- title: "Smart-Infinity: Fast Large Language Model Training using Near-Storage Processing on a Real System"
  authors:
    - Hongsun Jang
    - Jaeyong Song
    - Jaewon Jung
    - Jaeyoung Park
    - Youngsok Kim
    - Jinho Lee
  date: '2024-03-02'
  publisher: Best Paper Award-Honorable Mention, International Symposium on High-Performance Computer Architecture (HPCA)
  buttons:
    - type: arxiv
      link: http://arxiv.org/abs/2403.06664
    - type: github
      link: AIS-SNU/smart-infinity
    - type: video
      link: https://www.youtube.com/watch?v=o1O3-mQCSv4&feature=youtu.be
    - type: poster
      link: AIS-SNU/smart-infinity/blob/main/assets/smart-infinity_poster_hpca24.pdf
  tags:
    - Top Conf.
    - Syst. SW
    - Arch. 
    - AI/ML
  image: images_paper/smart_infinity.png
  id: 10.1109/HPCA57654.2024.00034

- id: 10.1109/TC.2023.3299030
  tags:
    - SCI
    - Arch. 
    - AI/ML
  buttons:
    - type: paper
      link: https://ieeexplore.ieee.org/abstract/document/10198513

- id: 10.1145/3589258
  tags:
    - Top Conf.
    - AI/ML
    - Syst. SW
  buttons:
    - type: paper
      link: https://dl.acm.org/doi/abs/10.1145/3589258

- id: 10.23919/DATE56975.2023.10137044
  tags:
    - Top Conf.
    - AI/ML
    - Syst. SW
  buttons:
    - type: paper
      link: https://ieeexplore.ieee.org/abstract/document/10137044
    - type: arxiv
      link: https://arxiv.org/abs/2301.12443
    - type: github
      link: hongsunjang/Pipe-BD
  image: images_paper/pipebd.png

- id: 10.1145/3575693.3575712
  authors:
    - Jaeyong Song<sup>1</sup>
    - Jinkyu Yim<sup>1</sup>
    - Jaewon Jung
    - Hongsun Jang
    - Hyung-Jin Kim
    - Youngsok Kim
    - Jinho Lee
  tags:
    - Top Conf.
    - AI/ML
    - Syst. SW
  buttons:
    - type: arxiv
      link: https://arxiv.org/abs/2301.09830
    - type: paper
      link: https://dl.acm.org/doi/10.1145/3575693.3575712
    - type: artifact
      link: https://zenodo.org/record/7220824

- id: 10.1145/3575693.3575712
  title: 'Optimus-CC: Efficient Large NLP Model Training with 3D Parallelism Aware
    Communication Compression'
  authors:
  - Jaeyong Song<sup>1</sup>
  - Jinkyu Yim<sup>1</sup>
  - Jaewon Jung
  - Hongsun Jang
  - Hyung-Jin Kim
  - Youngsok Kim
  - Jinho Lee
  publisher: Proceedings of the 28th ACM International Conference on Architectural
    Support for Programming Languages and Operating Systems, Volume 2
  date: '2023-01-27'
  link: https://doi.org/gtm365
  tags:
  - Top Conf.
  - AI/ML
  - Syst. SW
  buttons:
  - type: arxiv
    link: https://arxiv.org/abs/2301.09830
  - type: paper
    link: https://dl.acm.org/doi/10.1145/3575693.3575712
  - type: artifact
    link: https://zenodo.org/record/7220824
  image: images_paper/optimus_cc.png

- id: 10.1109/HPCA56546.2023.10071102
  authors:
    - Mingi Yoo<sup>1</sup>
    - Jaeyong Song<sup>1</sup>
    - Jounghoo Lee
    - Namhyung Kim
    - Youngsok Kim
    - Jinho Lee
  tags:
    - Top Conf.
    - Arch.
    - AI/ML
  buttons:
    - type: arxiv
      link: https://arxiv.org/abs/2301.10388
    - type: paper
      link: https://ieeexplore.ieee.org/document/10071102/

- id: https://bmvc2022.mpi-inf.mpg.de/281/
  title: Improving Gradient Paths for Binary Convolutional Neural Networks
  authors:
    - Baozhou Zhu
    - Peter Hofstee
    - Jinho Lee
    - Zaid Al-Ars
  tags:
    - Top Conf.
    - AI/ML
  buttons: 
    - type: paper
      link: https://bmvc2022.mpi-inf.mpg.de/0281.pdf
  date: '2022-11-21'
  publisher: BMVC

- id: 10.1145/3559009.3569693
  title: "Slice-and-Forge: Making Better Use of Caches for Graph Convolutional Network Accelerators"
  authors: 
    - Mingi Yoo<sup>1</sup>
    - Jaeyong Song<sup>1</sup>
    - Hye Yoon Lee
    - Jounghoo Lee
    - Namhyung Kim
    - Youngsok Kim
    - Jinho Lee
  tags:
    - Top Conf.
    - Arch. 
    - AI/ML
  publisher: PACT (Best Paper Award)
  buttons:
    - type: arxiv
      link: https://arxiv.org/abs/2301.09813
    - type: paper
      link: https://dl.acm.org/doi/10.1145/3559009.3569693

- id: 10.1145/3559009.3569686
  tags:
    - Top Conf.
    - Syst. SW
  buttons:
    - type: paper
      link: https://dl.acm.org/doi/10.1145/3559009.3569686

- id: 10.1145/3470496.3527384
  title: "GCoM: a detailed GPU core model for accurate analytical modeling of modern GPUs"
  tags:
    - Top Conf.
    - Arch.
  buttons:  
    - type: paper
      link: https://dl.acm.org/doi/10.1145/3470496.3527384

- id: 10.1145/3528535.3531513
  title: "GuardiaNN: Fast and Secure On-Device Inference in TrustZone Using Embedded SRAM and Cryptographic Hardware"
  tags:
    - Top Conf.
    - Syst. SW
    - AI/ML
  buttons:
    - type: paper
      link: https://dl.acm.org/doi/10.1145/3528535.3531513

- id: 10.1109/IPDPS53621.2022.00076
  image: images_paper/saloba.png
  tags: 
    - Top Conf.
    - Syst. SW
    - Bioinfo.
  buttons: 
    - type: paper
      link: https://ieeexplore.ieee.org/document/9820739/
    - type: arxiv
      link: https://arxiv.org/abs/2301.09310

- id: 10.1109/TC.2021.3092205
  tags: 
    - SCI
    - Arch.
    - AI/ML
  buttons:
    - type: paper
      link: https://ieeexplore.ieee.org/document/9470992

- id: 10.1109/LCA.2021.3090954
  authors: 
    - Mingi Yoo<sup>1</sup>
    - Jaeyong Song<sup>1</sup>
    - Jounghoo Lee
    - Namhyung Kim
    - Youngsok Kim
    - Jinho Lee
  tags:
    - SCI
    - Arch. 
    - AI/ML
  buttons:
    - type: video
      link: https://www.youtube.com/watch?v=72088TLwchY
    - type: paper
      link: https://ieeexplore.ieee.org/document/9461595

- id: https://www.ijcai.org/proceedings/2021/478
  title: "AutoReCon: Neural Architecture Search-based Reconstruction for Data-free Compression"
  authors:
    - Baozhou Zhu
    - Peter Hofstee
    - Johan Peltenburg
    - Jinho Lee
    - Zaid Al-Ars
  tags:
    - Top Conf.
    - AI/ML
  buttons: 
    - type: paper
      link: https://www.ijcai.org/proceedings/2021/0478.pdf
  date: '2021-08-19'
  publisher: IJCAI

- id: 10.1109/DAC18074.2021.9586312
  tags: 
    - Top Conf.
    - Arch. 
    - AI/ML
  buttons:
    - type: paper
      link: https://ieeexplore.ieee.org/document/9586312

- id: 10.1109/HPCA51647.2021.00030
  tags:
    - Top Conf.
    - Arch. 
    - AI/ML
  buttons:
    - type: arxiv
      link: https://arxiv.org/abs/2102.07511
    - type: paper
      link: https://ieeexplore.ieee.org/abstract/document/9407195
    - type: slide
      link: https://aisys.snu.ac.kr/papers/HPCA2021-GradPIM.pdf

- id: arxiv:2010.00823
  title: Deep Composer Classification Using Symbolic Representation
  authors:
    - Sunghyeon Kim<sup>1</sup>
    - Hyeyoon Lee<sup>1</sup>
    - Sunjong Park<sup>1</sup>
    - Jinho Lee
    - Keunwoo Choi
  publisher: LBD@ISMIR
  date: "2020-10-11"
  tags: 
    - AI/ML
  image: images_paper/deepcomposer.png
  buttons:
    - type: paper
      link: https://program.ismir2020.net/lbd_431.html
    - type: arxiv
      link: https://arxiv.org/abs/2010.00823
    - type: poster
      link: https://aisys.snu.ac.kr/papers/deep_composer_poster_1005.pdf

- id: 10.1109/DAC18072.2020.9218538
  tags: 
    - Top Conf.
    - AI/ML
    - Syst. SW
  buttons:
    - type: authorcopy
      link: https://aisys.snu.ac.kr/papers/FlexReduce_DAC_2020.pdf
    - type: paper
      link: https://ieeexplore.ieee.org/abstract/document/9218538

- id: 10.1109/CVPRW50498.2020.00385
  tags: 
    - AI/ML

- id: 10.1007/s11265-020-01547-w
  tags:
    - SCI
    - Arch.
  buttons:
    - type: paper
      link: https://link.springer.com/content/pdf/10.1007/s11265-020-01547-w.pdf


- id: 10.1007/s00778-019-00581-w
  tags: 
    - SCI
    - Arch.
  buttons:
  - type: paper
    link: https://link.springer.com/article/10.1007/s00778-019-00581-w

- id: https://arxiv.org/abs/2001.04893
  tags:
    - AI/ML
  buttons:
    - type: arxiv
      link: https://arxiv.org/abs/2001.04893
  publisher: arXiv preprint

- id: 10.1109/ICCVW.2019.00188

- id: 10.1109/ASAP.2019.00017

- id: 10.1145/3335783.3335786

- id: 10.1109/MPRV.2019.2907004

- id: 10.1109/MDAT.2018.2890238

- id: 10.1016/j.neucom.2018.05.087

- id: 10.1145/3210240.3210348

- id: https://arxiv.org/abs/1802.03057

- id: 10.1109/BigData.2017.8258092

- title: "Analyzing In-Memory Hash Joins: Granularity Matters"
  authors:
    - Jian Fang
    - Jinho Lee
    - Peter Hofstee
    - Jan Hidders
  publisher: ADMS workshop @VLDB
  date: "2017-08-28"
  buttons:
    - type: paper
      link: https://adms-conf.org/2017/camera-ready/Analyzing_In_Memory_Hash_Joins__Granularity_Matters.pdf
  id: ""

- title: "ExtraV: boosting graph processing near storage with a coherent accelerator"
  authors:
    - Jinho Lee
    - Heesu Kim
    - Sungjoo Yoo
    - Kiyoung Choi
    - H. Peter Hofstee
    - Gi-Joon Nam
    - Mark R. Nutter
    - Damir Jamsek
  publisher: Proceedings of the VLDB Endowment
  date: "2017-08-01"
  buttons:
    - type: paper
      link: https://dl.acm.org/doi/10.14778/3137765.3137776
  id: 10.14778/3137765.3137776

- id: 10.1109/MDM.2017.45

- id: 10.1109/TCAD.2017.2693269

- id: 10.1109/TVLSI.2017.2655722

- title: "Buffered compares: excavating the hidden parallelism inside DRAM architectures with lightweight logic"
  authors:
    - Jinho Lee
    - Jung Ho Ahn
    - Kiyoung Choi
  publisher: 2016 Design, Automation and Test in Europe Conference (DATE)
  date: "2016-03-14"
  buttons:
    - type: paper
      link: https://dl.acm.org/doi/abs/10.5555/2971808.2972099
  id: 10.3850/9783981537079_0512

- title: "REDELF: An Energy-Efficient Deadlock-Free Routing for 3D NoCs with Partial Vertical Connections"
  authors:
    - Jinho Lee
    - Kyungsu Kang
    - Kiyoung Choi
  publisher: ACM Journal on Emerging Technologies in Computing Systems (JETC)
  date: "2015-09-21"
  buttons:
    - type: paper
      link: https://dl.acm.org/doi/10.1145/2751560
  id: 10.1145/2751560

- id: 10.1109/ASPDAC.2015.7059104

- id: 10.1145/2685342.2685346

- id: 10.1145/2536522.2536534

- id: 10.1109/TCAD.2013.2266405

- id: 10.1145/2505011

- id: 10.1109/NoCS.2013.6558407

- id: 10.1109/ASPDAC.2013.6509554

- id: 10.1109/VLSI-SoC.2012.6378999

- id: 10.1109/ASPDAC.2012.6164985

- id: 10.1109/isocc.2011.6138783

- id: 10.1109/SOCDC.2009.5423916








- id: 10.1109/DAC18074.2021.9586121
  type: paper
  image: images_paper/dance.png
  authors:
    - Kanghyun Choi<sup>1</sup>
    - Deokki Hong<sup>1</sup>
    - Hojae Yoon<sup>1</sup>
    - Joonsang Yu 
    - Youngsok Kim
    - Jinho Lee
  buttons:
    - type: arxiv
      link: https://arxiv.org/abs/2009.06237
    - type: slide
      link: resources_paper/dance_slides.pdf
  publisher: Design Automation Conference (DAC)
  tags:
    - Top Conf. 
    - AI/ML 
    - Arch.

- id: arxiv:2111.02625
  type: paper
  image: images_paper/qimera.png
  publisher: Neural Information Processing Systems (NeurIPS)
  buttons:
    - type: arxiv
      link: https://arxiv.org/abs/2111.02625
    - type: slide
      link: resources_paper/qimera_slides.pdf
    - type: github
      link: iamkanghyunchoi/qimera
  tags:
    - Top Conf. 
    - AI/ML 

- id: arxiv:2301.09312
  type: paper
  image: images_paper/hdx.png
  publisher: Design Automation Conference (DAC)
  buttons:
    - type: arxiv
      link: https://arxiv.org/abs/2301.09312
  tags:
    - Top Conf. 
    - AI/ML 
    - Arch.

- id: arxiv:2203.17008
  type: paper
  image: images_paper/ait.png
  publisher: Computer Vision and Pattern Recognition Conference (CVPR)
  buttons:
    - type: arxiv
      link: https://arxiv.org/abs/2203.17008
    - type: slide
      link: resources_paper/cvpr_ait.pdf
    - type: github
      link: iamkanghyunchoi/ait
  tags:
    - Top Conf. 
    - AI/ML 

- id: 10.1109/DAC56929.2023.10247930
  type: paper
  image: images_paper/dbac.png
  publisher: Design Automation Conference (DAC)
  tags:
    - Top Conf. 
    - AI/ML 
