- id: doi:10.1109/DAC18074.2021.9586121
  type: paper
  image: images_paper/dance.png
  authors:
    - Kanghyun Choi<sup>1</sup>
    - Deokki Hong<sup>1</sup>
    - Hojae Yoon<sup>1</sup>
    - Joonsang Yu 
    - Youngsok Kim
    - Jinho Lee
  buttons:
    - type: arxiv
      link: https://arxiv.org/abs/2009.06237
    - type: slide
      link: resources_paper/dance_slides.pdf
  publisher: Design Automation Conference (DAC)
  tags:
    - Top Conf. 
    - AI/ML 
    - Arch.

- id: arxiv:2111.02625
  type: paper
  image: images_paper/qimera.png
  publisher: Neural Information Processing Systems (NeurIPS)
  buttons:
    - type: arxiv
      link: https://arxiv.org/abs/2111.02625
    - type: slide
      link: resources_paper/qimera_slides.pdf
    - type: github
      link: https://github.com/iamkanghyunchoi/qimera
  tags:
    - Top Conf. 
    - AI/ML 

- id: arxiv:2301.09312
  type: paper
  image: images_paper/hdx.png
  publisher: Design Automation Conference (DAC)
  buttons:
    - type: arxiv
      link: https://arxiv.org/abs/2301.09312
  tags:
    - Top Conf. 
    - AI/ML 
    - Arch.

- id: arxiv:2203.17008
  type: paper
  image: images_paper/ait.png
  publisher: Neural Information Processing Systems (NeurIPS)
  buttons:
    - type: arxiv
      link: https://arxiv.org/abs/2203.17008
    - type: slide
      link: resources_paper/cvpr_ait.pdf
    - type: github
      link: https://github.com/iamkanghyunchoi/ait
  tags:
    - Top Conf. 
    - AI/ML 

- id: doi:10.1109/DAC56929.2023.10247930
  type: paper
  image: images_paper/dbac.png
  publisher: Design Automation Conference (DAC)
  tags:
    - Top Conf. 
    - AI/ML 